// user-profile.component.ts
import { Component, Input } from '@angular/core';

export interface UserProfile {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  address: string;
  bio: string;
  avatar?: string;
}

@Component({
  selector: 'app-user-profile',
  template: `
    <div class="profile-container">
      <div class="profile-header">
        <img 
          [src]="user.avatar || 'https://via.placeholder.com/150' + 
                '?text=' + user.firstName.charAt(0) + user.lastName.charAt(0)" 
          alt="Profile picture" 
          class="profile-avatar">
        <div class="profile-basic-info">
          <h1>{{ user.firstName }} {{ user.lastName }}</h1>
          <p class="profile-email">{{ user.email }}</p>
        </div>
      </div>
      
      <div class="profile-details">
        <div class="detail-item">
          <strong>Phone:</strong> {{ user.phone }}
        </div>
        <div class="detail-item">
          <strong>Address:</strong> {{ user.address }}
        </div>
        <div class="detail-item">
          <strong>Bio:</strong> {{ user.bio }}
        </div>
      </div>
    </div>
  `,
  styles: [`
    .profile-container {
      max-width: 600px;
      margin: 20px auto;
      padding: 20px;
      border: 1px solid #ddd;
      border-radius: 8px;
      font-family: Arial, sans-serif;
      box-shadow: 0 2px 10px rgba(0,0,0,0.1);
    }
    
    .profile-header {
      display: flex;
      align-items: center;
      margin-bottom: 20px;
    }
    
    .profile-avatar {
      width: 100px;
      height: 100px;
      border-radius: 50%;
      margin-right: 20px;
      object-fit: cover;
    }
    
    .profile-basic-info h1 {
      margin: 0 0 5px 0;
      color: #333;
    }
    
    .profile-email {
      margin: 0;
      color: #666;
      font-style: italic;
    }
    
    .profile-details {
      margin-top: 20px;
    }
    
    .detail-item {
      margin-bottom: 15px;
      padding-bottom: 10px;
      border-bottom: 1px solid #eee;
    }
    
    .detail-item strong {
      display: inline-block;
      width: 80px;
      color: #555;
    }
  `]
})
export class UserProfileComponent {
  @Input() user!: UserProfile;
}

// UserProfile.jsx
import React from 'react';

const UserProfile = ({ user }) => {
  const { firstName, lastName, email, phone, avatar, bio, location } = user;

  return (
    <div className="user-profile">
      <div className="profile-header">
        {avatar ? (
          <img 
            src={avatar} 
            alt={`Avatar of ${firstName} ${lastName}`}
            className="avatar"
          />
        ) : (
          <div className="default-avatar">
            {firstName.charAt(0)}{lastName.charAt(0)}
          </div>
        )}
        <div className="user-info">
          <h1>{firstName} {lastName}</h1>
          <p className="user-title">{bio || 'User Profile'}</p>
        </div>
      </div>
      
      <div className="profile-details">
        <div className="detail-item">
          <strong>Email:</strong>
          <span>{email}</span>
        </div>
        <div className="detail-item">
          <strong>Phone:</strong>
          <span>{phone}</span>
        </div>
        {location && (
          <div className="detail-item">
            <strong>Location:</strong>
            <span>{location}</span>
          </div>
        )}
      </div>
    </div>
  );
};

export default UserProfile;
